### ISSUE TITLE
Migration does not work

### ISSUE THREAD

**Issue by MrFibunacci** [FramyFramework/Framy#25]
**Describe the bug**
`PHP Notice:  Undefined variable: output in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function writeln() on null in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php:70
Stack trace:
#0 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php(35): app\framework\Component\Database\Migrations\Commands\Migrate->setMigrations()
#1 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Console/Command/Command.php(132): app\framework\Component\Database\Migrations\Commands\Migrate->execute(Object(app\framework\Component\Console\Input\ArgvInput), Object(app\framework\Component\Console\Output\ConsoleOutput))
#2 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Console/Kernel.php(133): app\framework\Component\Console\Command\Command->run(Object(app\framework\Component\Console\Input\ArgvInput), Object(app\framework\Component\Console\Output\ConsoleOutput))
#3 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Com in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php on line 70
mrfibunacci@robin:~/PhpstormProjects/mrfibunacci$ php Framy migrate
PHP Notice:  Undefined variable: output in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function writeln() on null in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php:70
Stack trace:
#0 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php(35): app\framework\Component\Database\Migrations\Commands\Migrate->setMigrations()
#1 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Console/Command/Command.php(132): app\framework\Component\Database\Migrations\Commands\Migrate->execute(Object(app\framework\Component\Console\Input\ArgvInput), Object(app\framework\Component\Console\Output\ConsoleOutput))
#2 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Console/Kernel.php(133): app\framework\Component\Console\Command\Command->run(Object(app\framework\Component\Console\Input\ArgvInput), Object(app\framework\Component\Console\Output\ConsoleOutput))
#3 /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Com in /home/mrfibunacci/PhpstormProjects/mrfibunacci/app/framework/Component/Database/Migrations/Commands/Migrate.php on line 70`

**To Reproduce**
1. php Framy migrate
2. See error

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Version: v0.4

**Comment by MrFibunacci** [comment]
Fixing this should be easy:

in class `\app\framework\Component\Database\Migrations\Commands\Migrate` in method `execute()` the method `setMigrations()` is called. Within of `setMigrations` the value $output is used. Simply pass the $input and $output values to the `setMigrations()` method and this should be fixed!
