### ISSUE TITLE
Console throwing error

### ISSUE THREAD

**Issue by MrFibunacci** [FramyFramework/Framy#7]
**Describe the bug**
By running the basic command `php Framy` the following exception is thrown:

```
PHP Fatal error:  Uncaught Error: Call to undefined function app\framework\Component\Console\Helper\mb_detect_encoding() in /var/www/Framy/app/framework/Component/Console/Helper/Helper.php:26
Stack trace:
#0 /var/www/Framy/app/framework/Component/Console/Output/Descriptor/TextDescriptor.php(319): app\framework\Component\Console\Helper\Helper::strlen('h')
#1 /var/www/Framy/app/framework/Component/Console/Output/Descriptor/TextDescriptor.php(94): app\framework\Component\Console\Output\Descriptor\TextDescriptor->calculateTotalWidthForOptions(Array)
#2 /var/www/Framy/app/framework/Component/Console/Output/Descriptor/TextDescriptor.php(197): app\framework\Component\Console\Output\Descriptor\TextDescriptor->describeInputDefinition(Object(app\framework\Component\Console\Input\InputDefinition), Array)
#3 /var/www/Framy/app/framework/Component/Console/Output/Descriptor/Descriptor.php(45): app\framework\Component\Console\Output\Descriptor\TextDescriptor->describeApplication(Object(app\framework\Component\Console\Kernel), Array)
#4 /var/ in /var/www/Framy/app/framework/Component/Console/Helper/Helper.php on line 26
```

**To Reproduce**
1. Go to Terminal
2. Enter command from above
3. See error

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v0.3

**Comment by MrFibunacci** [comment]
Isn't a real bug just an issue with missing PHP module `mbstring`. Opened an issue saying that we need to add `mbstring` module to requirements.
